# Generated by Django 5.2.8 on 2025-12-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ کل (تومان)'),
        ),
    ]
