# Generated by Django 5.2.8 on 2025-11-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کدملی'),
        ),
    ]
