# Generated by Django 5.2.8 on 2025-11-17 11:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('initiated', 'شروع\u200cشده'), ('success', 'موفق'), ('failed', 'ناموفق')], default='initiated', max_length=20, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه تراکنش')),
                ('gateway', models.CharField(default='mock', max_length=50, verbose_name='درگاه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
    ]
