# Generated by Django 5.2.8 on 2025-11-17 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش\u200cها')),
            ],
            options={
                'verbose_name': 'کد تأیید',
                'verbose_name_plural': 'کدهای تأیید',
                'indexes': [models.Index(fields=['phone', 'created_at'], name='account_mob_phone_fac1cf_idx')],
            },
        ),
    ]
