# Generated by Django 5.2.8 on 2025-11-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileotp',
            name='code',
            field=models.CharField(max_length=64, verbose_name='کد'),
        ),
    ]
